language: java
sudo: true
jdk:
  - openjdk8

services:
  - docker

branched:
  only:
    - master

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '$HOME/docker'

env:
  global:
    - STABLE_TAG: 2.0
    - SPRING_PROFILES_ACTIVE: dev

install: true

before_install:
  - chmod +x mvnw
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

jobs:
  include:
    - stage: Maven Test the Project
      script:
        - ./mvnw -e clean package jacoco:report coveralls:report

    - stage: Docker Build & Deploy
      script:
        - ./mvnw -e clean package -DskipTests
        - mkdir deploy
        - cp ./target/*.jar ./deploy
        - cp ./docker/* ./deploy
        - docker login https://docker.pkg.github.com -u $GITHUB_PACKAGE_USERNAME -p $GITHUB_PACKAGE_PASSWORD
        - TAG="${STABLE_TAG}.${TRAVIS_BUILD_NUMBER}"
        - TAGGED_IMAGE="docker.pkg.github.com/misoboy/misoboy-api/misoboy-api"
        - IMAGE="${TAGGED_IMAGE}:${TAG}"
        - echo 'image:' $IMAGE
        - docker build --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE -t "$IMAGE" ./deploy/
        - docker push "${IMAGE}"

    - stage: ArgoCD Deploy
      script:
        - TAG="${STABLE_TAG}.${TRAVIS_BUILD_NUMBER}"
        - git clone -b argocd_canary https://github.com/misoboy/misoboy-api.git /tmp/misoboy-api
        - cd /tmp/misoboy-api
        - sed -i -E 's/(misoboy-api\:)(([0-9])|(\.)){1,}/misoboy-api:'$TAG'/' ./k8s/api-rollout.yml
        - git add .
        - git config credential.helper 'cache --timeout=120'
        - git config user.email "misoboy.kor@gmail.com"
        - git config user.name "misoboy"
        - git commit -m "Update via TravisCI"
        - git push -q https://$GITHUB_PACKAGE_PASSWORD@github.com/misoboy/misoboy-api.git argocd_canary

notifications:
  email:
    - misoboy.report@gmail.com
