version: 2
defaults:
  environment:

jobs:
  build_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      # run test
      - run:
          name : Maven Test the Project
          command : |
            chmod +x mvnw
            ./mvnw -e test

workflows:
  version: 2
  workflow:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
