version: 2
defaults:
  environment:

jobs:
  build_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci

      # run test
      - run:
          name : Maven Test the Project
          command : |
            chmod +x mvnw
            ./mvnw -e clean test jacoco:report coveralls:report
            mkdir deploy
            pwd
            ls -al
            ls -al ./target
            ls -al ./docker
            ls -al ./k8s
            cp ./target/*.jar ./deploy
            mv ./docker ./deploy
            mv ./k8s ./deploy

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - deploy

  build_deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Docker Build & Deploy
          command: |
            pwd
            ls -al
            ls -al ./deploy
            docker login https://docker.pkg.github.com -u $GITHUB_PACKAGE_USERNAME -p $GITHUB_PACKAGE_PASSWORD
            STABLE_TAG='1.0'
            TAG="${STABLE_TAG}.${CIRCLE_BUILD_NUM}"
            TAGGED_IMAGE="docker.pkg.github.com/misoboy/misoboy-api/misoboy-api"
            IMAGE="${TAGGED_IMAGE}:${TAG}"
            echo "image: $IMAGE"
            docker build -t "$IMAGE" ./deploy/docker/
            docker push "${IMAGE}"

workflows:
  version: 2
  workflow:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
      - build_deploy:
          context: GITHUB_SECRET
          requires:
            - build_test
          filters:
            branches:
              only: master
