version: 2
defaults:
  environment:

jobs:
  build_test:
    docker:
      - image: maven:3-openjdk-8
    steps:
      - checkout
      # run test
      - run:
          name : Maven Test the Project
          command : |
            chmod +x mvnw
            ./mvnw surefire:test

workflows:
  version: 2
  workflow:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
