kind: Service
apiVersion: v1
metadata:
  name: app-api-service-active
spec:
  selector:
    misoboy-service: app-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
      name: http
