apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-api-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      misoboy-service: app-api
  template:
    metadata:
      labels:
        misoboy-service: app-api
    spec:
      containers:
      - name: app-api
        image: docker.pkg.github.com/misoboy/misoboy-api/misoboy-api:2.0.6
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: regcred
  strategy:
    canary: # 카나리아 전략에 구성 가능한 옵션을 제공하는 데 사용되는 새로운 필드
      steps:
      - setWeight: 20 # 카나리아로 전송해야하는 트래픽의 백분율.
      #- pause: {} # 롤아웃을 일시 중시하도록 지시한다. 
        # pause 구조체 내에 duration 필드가 설정되어 있으면 duration 필드의 값만큼 기다린 후 롤아웃을 진행한다.
        # 그렇지 않으면, 일시 중지 조건이 제거될 때 까지 롤아웃이 무기한 대기한다.

---
kind: Service
apiVersion: v1
metadata:
  name: app-api-service-active
spec:
  selector:
    misoboy-service: app-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
