apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deploy
  labels:
    misoboy-service: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      misoboy-service: app-api
  template:
    metadata:
      labels:
        misoboy-service: app-api
    spec:
      containers:
        - name: app-api
          image: docker.pkg.github.com/misoboy/misoboy-api/misoboy-api:$TAG
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred
